const $ = (selector) => document.querySelector(selector);
const topicList = $('#topic-list');
const themeToggle = $('#theme-toggle');
const sections = [
['C# Introduction & Setup','Introduction to C#|History of C#|Features of C#|Applications of C#|C# vs C++|C# vs Java|.NET Introduction|.NET Framework|.NET Core|Modern .NET|CLR|CTS|CLS|C# Installation & Setup|Installing .NET SDK|Visual Studio Setup|Visual Studio Code Setup|Creating First C# Project|First C# Program|Build and Run|C# Program Structure|Comments in C#'],
['C# Basic Syntax','Basic Syntax|Keywords|Identifiers|Variables|Constants|Data Types|Value Types|Reference Types|Integral Types|Floating-Point Types|Decimal Type|Boolean Type|Character Type|String Type|Object Type|var Keyword|dynamic Keyword|Nullable Types|Literals|Type Conversion|Type Casting|Implicit Conversion|Explicit Conversion|Parse()|TryParse()|Convert Class'],
['Input & Output','Console Introduction|Console.Write()|Console.WriteLine()|Console.Read()|Console.ReadLine()|Console.ReadKey()|String Interpolation|Composite Formatting|Output Formatting|Escape Sequences'],
['Operators','Operators Introduction|Arithmetic Operators|Relational Operators|Equality Operators|Logical Operators|Assignment Operators|Unary Operators|Increment Operator|Decrement Operator|Bitwise Operators|Shift Operators|Compound Assignment Operators|Null-Coalescing Operator|Null-Conditional Operator|Ternary Operator|typeof Operator|is Operator|as Operator|sizeof Operator|nameof Operator|Operator Precedence'],
['Conditional Statements','if Statement|if-else Statement|Nested if|else-if Statement|switch Statement|switch Expression|Pattern Matching with switch|Nested switch|Conditional Operator'],
['Loops','for Loop|while Loop|do-while Loop|foreach Loop|Nested Loops|break Statement|continue Statement|goto Statement|Infinite Loops'],
['Methods','Methods|Method Declaration|Method Calling|Method Parameters|Return Values|Method Overloading|Static Methods|Instance Methods|Optional Parameters|Named Arguments|ref Parameters|out Parameters|in Parameters|params Keyword|Expression-Bodied Methods|Local Functions|Recursive Methods'],
['Strings','String Introduction|Creating Strings|String Properties|String Methods|String Length|Character Access|String Concatenation|String Comparison|String Interpolation|String Formatting|String Searching|String Slicing|Substring()|Contains()|StartsWith()|EndsWith()|Replace()|Split()|Join()|Trim()|ToUpper()|ToLower()|StringBuilder|String Immutability'],
['Arrays','Introduction to Arrays|Array Declaration|Array Initialization|1D Array|Array Traversal|Array Input and Output|Array Sorting|Array Searching|2D Array|Multidimensional Array|Jagged Array|Array of Objects|Array Class|Copying Arrays'],
['Collections','Collections Introduction|ArrayList|List<T>|LinkedList<T>|Dictionary<TKey,TValue>|SortedDictionary|SortedList|HashSet<T>|SortedSet<T>|Stack<T>|Queue<T>|Concurrent Collections|Collection Initializers|Iterating Collections'],
['Object-Oriented Programming','OOP Introduction|Classes|Objects|Fields|Properties|Methods in Classes|Constructors|Default Constructor|Parameterized Constructor|Constructor Overloading|Static Constructor|Copy Constructor Concept|this Keyword|static Keyword|readonly Keyword|const Keyword'],
['Encapsulation','Encapsulation|Access Modifiers|public|private|protected|internal|protected internal|private protected|Getters and Setters|Auto-Implemented Properties|Property Accessors|Init-Only Properties'],
['Inheritance','Inheritance|Base Class|Derived Class|Single Inheritance|Multilevel Inheritance|Hierarchical Inheritance|Multiple Inheritance using Interfaces|base Keyword|Constructor in Inheritance|Method Hiding|new Keyword'],
['Polymorphism','Polymorphism|Compile-Time Polymorphism|Runtime Polymorphism|Method Overloading|Method Overriding|virtual Keyword|override Keyword|sealed Keyword|Dynamic Polymorphism|Upcasting|Downcasting'],
['Abstraction','Abstraction|Abstract Class|Abstract Method|Abstract Properties|Interface|Implementing Interface|Multiple Interfaces|Interface Inheritance|Explicit Interface Implementation|Default Interface Methods|Interface vs Abstract Class'],
['Structs & Enums','Structures|Struct vs Class|Struct Constructors|readonly Struct|Enumerations|Enum Members|Enum Methods|Enum Parsing|Flags Enum'],
['Delegates & Events','Delegates|Single-Cast Delegate|Multicast Delegate|Generic Delegates|Action Delegate|Func Delegate|Predicate Delegate|Anonymous Methods|Events|Event Handlers|Custom Events'],
['Exception Handling','Exception Handling|Errors vs Exceptions|Exception Hierarchy|try Block|catch Block|finally Block|throw Keyword|Multiple catch|Nested try-catch|Custom Exceptions|Exception Filters|Inner Exception|Common Exceptions|Best Practices for Exception Handling'],
['Generics','Generics Introduction|Generic Classes|Generic Methods|Generic Interfaces|Generic Delegates|Multiple Type Parameters|Generic Constraints|where Constraint|Nullable Generic Types'],
['Interfaces & Advanced OOP','Interface Design|Interface Segregation|Dependency Inversion|Composition|Aggregation|Association|Sealed Classes|Partial Classes|Partial Methods|Extension Methods'],
['LINQ','Introduction to LINQ|LINQ Query Syntax|LINQ Method Syntax|Where()|Select()|SelectMany()|OrderBy()|OrderByDescending()|ThenBy()|GroupBy()|Join()|Aggregate Functions|First()|FirstOrDefault()|Single()|SingleOrDefault()|Any()|All()|Contains()|Count()|Sum()|Average()|Min()|Max()|Distinct()|Skip()|Take()|ToList()|ToArray()|ToDictionary()'],
['File Handling & I/O','File Handling Introduction|File Class|Directory Class|FileInfo|DirectoryInfo|FileStream|StreamReader|StreamWriter|BinaryReader|BinaryWriter|Path Class|Reading Text Files|Writing Text Files|Copying Files|Moving Files|Deleting Files|Working with Directories'],
['Serialization','Serialization Introduction|JSON Serialization|JSON Deserialization|System.Text.Json|XML Serialization|Binary Serialization Concept|Custom Serialization'],
['Multithreading','Introduction to Threads|Thread Class|Creating Threads|Thread.Start()|Thread.Sleep()|Thread.Join()|Thread Priority|Thread Synchronization|lock Keyword|Monitor|Mutex|Semaphore|Deadlock|Race Conditions|Thread Safety'],
['Asynchronous Programming','Synchronous vs Asynchronous|Task|Task<TResult>|async Keyword|await Keyword|async Methods|Task.WhenAll()|Task.WhenAny()|CancellationToken|ValueTask|Parallel Programming|Parallel.For|Parallel.ForEach|Concurrent Programming'],
['Memory Management','Stack and Heap|Managed Memory|Garbage Collection|Generations in GC|IDisposable|Dispose Pattern|using Statement|using Declaration|Weak References|Memory Leaks'],
['Modern C# Features','Pattern Matching|Property Patterns|Tuple Patterns|Switch Expressions|Records|Record Structs|Init Accessors|Nullable Reference Types|Global Using|File-Scoped Namespace|Top-Level Statements|Raw String Literals|Required Members|Primary Constructors|Collection Expressions|List Patterns'],
['Regular Expressions','Regular Expressions|Regex Class|Regex Patterns|Character Classes|Quantifiers|Groups|Regex Matching|Regex Replacement|Regex Validation'],
['Reflection & Attributes','Reflection|Type Class|Assembly Class|MethodInfo|PropertyInfo|FieldInfo|Attributes|Built-in Attributes|Custom Attributes|Attribute Reflection'],
['Networking','Networking Introduction|HttpClient|HTTP GET Request|HTTP POST Request|HTTP PUT Request|HTTP DELETE Request|HttpRequestMessage|HttpResponseMessage|JSON API Communication|Socket Programming|TCP Client|TCP Server|UDP Networking'],
['Database & ADO.NET','Database Introduction|ADO.NET|Database Connection|SqlConnection|SqlCommand|SqlDataReader|SqlDataAdapter|DataSet|DataTable|ExecuteNonQuery()|ExecuteScalar()|ExecuteReader()|CRUD Operations|Parameterized Queries|Transactions|Connection Pooling'],
['ASP.NET Core','Introduction to ASP.NET Core|ASP.NET Core Setup|Project Structure|Middleware|Dependency Injection|Configuration|Routing|Controllers|Action Methods|Model Binding|Model Validation|Razor Pages|Razor Syntax|Views|ViewBag|ViewData|TempData|Tag Helpers|Web API|REST API|API Controllers|HTTP Status Codes|Swagger / OpenAPI'],
['Authentication & Security','Authentication|Authorization|Identity|Password Hashing|Role-Based Authorization|Claims-Based Authorization|JWT Authentication|Cookies Authentication|CORS|CSRF Protection|HTTPS|Secrets Management'],
['Desktop GUI','Windows Forms Introduction|Creating WinForms Application|Form|Label|TextBox|Button|CheckBox|RadioButton|ComboBox|ListBox|DataGridView|Event Handling|WPF Introduction|XAML|WPF Controls|Data Binding'],
['Testing & Debugging','Debugging Introduction|Breakpoints|Watch Window|Step Into|Step Over|Step Out|Unit Testing|xUnit|NUnit|Assertions|Mocking|Test-Driven Development'],
['Design Patterns','Design Patterns Introduction|Singleton Pattern|Factory Pattern|Abstract Factory|Builder Pattern|Prototype Pattern|Adapter Pattern|Decorator Pattern|Facade Pattern|Proxy Pattern|Observer Pattern|Strategy Pattern|Command Pattern|Repository Pattern|Dependency Injection Pattern'],
['C# Practice','Basic C# Programs|Number Programs|Pattern Programs|String Programs|Array Programs|OOP Programs|LINQ Programs|Exception Handling Programs|File Handling Programs|Multithreading Programs|Database Programs|API Programs'],
['C# Projects','Calculator|Number Guessing Game|To-Do List|Student Management System|Employee Management System|Library Management System|Banking System|Inventory Management System|File Manager|Quiz Application|Weather Application|REST API Project|ASP.NET Core Web Application|E-Commerce Application|Full-Stack C# Project']
].map(([title, lessons]) => ({ title, lessons: lessons.split('|') }));
const allLessons = sections.flatMap((section) => section.lessons);
const buildLessonTheory = (lesson, section, code) => {
	const name = lesson.toLowerCase();
	let explanation = `This lesson teaches ${lesson}, a C# building block used in the ${section.title} module. It helps you create readable, type-safe applications on .NET.`;
	let syntax = 'Read the example line by line, run it, then change one value and observe the result.';
	if (name.includes('variable') || name.includes('constant') || name.includes('data type')) { explanation = 'A variable is a named storage location. C# is strongly typed, so the compiler checks what kind of value a variable can hold and how it may be used.'; syntax = 'Use `type name = value;`, or `var` when the compiler can infer the type.'; }
	else if (name.includes('loop') || name.includes('break') || name.includes('continue')) { explanation = 'A loop repeats a block of code. `for` is useful for indexed work, while `foreach` is designed to visit every item in a collection.'; syntax = 'Set a clear condition and update value so the loop eventually stops.'; }
	else if (name.includes('array') || name.includes('list') || name.includes('collection')) { explanation = 'Collections store multiple values. Arrays have a fixed size, while `List<T>` and other collection types provide flexible operations for real applications.'; syntax = 'Choose the collection based on whether you need indexing, uniqueness, ordering, or key-value lookup.'; }
	else if (name.includes('class') || name.includes('object') || name.includes('constructor')) { explanation = 'A class describes data and behavior; an object is a usable instance of that class. Properties expose state and methods perform actions.'; syntax = 'Define a class, create an object with `new`, then call its members.'; }
	else if (name.includes('exception') || name.includes('try') || name.includes('catch')) { explanation = 'Exceptions report problems that happen during execution. Handling them keeps the application predictable and lets you show a useful response instead of crashing silently.'; syntax = 'Put risky code inside `try`, handle expected failures in `catch`, and clean up in `finally` when needed.'; }
	else if (name.includes('linq')) { explanation = 'LINQ lets you query collections using readable C# expressions. A query can filter, transform, sort, group, and aggregate data without manual loops.'; syntax = 'Start with a collection, chain methods such as `Where` and `Select`, then materialize with `ToList` if needed.'; }
	else if (name.includes('async') || name.includes('task') || name.includes('thread')) { explanation = 'Asynchronous and concurrent code keeps applications responsive while work runs in the background. A `Task` represents work that may finish later.'; syntax = 'Mark a method `async`, await its task, and handle cancellation or errors deliberately.'; }
	return `<p><strong>What is ${lesson}?</strong></p><p>${explanation}</p><p><strong>Syntax:</strong> ${syntax}</p><p><strong>Expected result:</strong> Running the example demonstrates the main behavior of ${lesson}.</p><div class="lesson-example"><h4>Example</h4><pre>${code}</pre></div><h4 class="lesson-reference-title">Remember</h4><ul><li>C# is case-sensitive and strongly typed.</li><li>Use meaningful names and let the compiler find mistakes.</li><li>Change one input, predict the output, then run it.</li></ul><h4 class="lesson-reference-title">Topic Reference</h4><table class="lesson-table"><thead><tr><th>Item</th><th>Lesson-specific detail</th></tr></thead><tbody><tr><td>Concept</td><td>${lesson}</td></tr><tr><td>Syntax</td><td>${syntax}</td></tr><tr><td>Practice</td><td>Modify the example and compare the new output.</td></tr></tbody></table>`;
};
let activeSection = 0;
let activeLesson = 0;
const codeFor = (lesson) => { const name = lesson.toLowerCase(); if (name.includes('loop') || name.includes('foreach')) return 'using System;\n\nclass Program {\n    static void Main() {\n        for (int i = 1; i <= 5; i++) Console.WriteLine(i);\n    }\n}'; if (name.includes('array') || name.includes('list')) return 'using System;\n\nclass Program {\n    static void Main() {\n        int[] numbers = { 3, 1, 2 };\n        Array.Sort(numbers);\n        Console.WriteLine(string.Join(", ", numbers));\n    }\n}'; if (name.includes('string')) return 'using System;\n\nclass Program {\n    static void Main() {\n        string message = "Hello C#";\n        Console.WriteLine(message.ToUpper());\n    }\n}'; if (name.includes('exception') || name.includes('try') || name.includes('catch')) return 'using System;\n\nclass Program {\n    static void Main() {\n        try { int result = 10 / 0; }\n        catch (DivideByZeroException) { Console.WriteLine("Cannot divide by zero"); }\n    }\n}'; if (name.includes('class') || name.includes('object') || name.includes('constructor')) return 'class Student { public string Name { get; set; } = "Asha"; }\n\nclass Program {\n    static void Main() {\n        var student = new Student();\n        System.Console.WriteLine(student.Name);\n    }\n}'; return `using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("${lesson}");\n    }\n}`; };
function renderTopics() { sections.forEach((section, sectionIndex) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'cs-topic'; button.dataset.section = sectionIndex; button.innerHTML = `<span>${sectionIndex + 1}. ${section.title}</span><i class="fa-solid fa-chevron-right topic-arrow" aria-hidden="true"></i>`; const lessons = document.createElement('div'); lessons.className = 'cs-subtopics'; lessons.id = `cs-section-${sectionIndex}`; section.lessons.forEach((lesson, lessonIndex) => { const item = document.createElement('button'); item.type = 'button'; item.className = 'cs-subtopic'; item.textContent = `${lessonIndex + 1}. ${lesson}`; item.addEventListener('click', () => loadLesson(sectionIndex, lessonIndex)); lessons.appendChild(item); }); button.addEventListener('click', () => { const open = lessons.classList.toggle('open'); button.classList.toggle('expanded', open); if (open) loadLesson(sectionIndex, 0); }); topicList.append(button, lessons); }); $('#lesson-count').textContent = allLessons.length; }
function loadLesson(sectionIndex, lessonIndex) { activeSection = sectionIndex; activeLesson = lessonIndex; const section = sections[sectionIndex]; const lesson = section.lessons[lessonIndex]; const button = topicList.querySelector(`[data-section="${sectionIndex}"]`); const container = $(`#cs-section-${sectionIndex}`); container.classList.add('open'); button.classList.add('expanded', 'active'); topicList.querySelectorAll('.cs-topic').forEach((item, index) => item.classList.toggle('active', index === sectionIndex)); container.querySelectorAll('.cs-subtopic').forEach((item, index) => item.classList.toggle('active', index === lessonIndex)); $('#page-title').textContent = `${sectionIndex + 1}. ${section.title}`; $('#topic-title').textContent = lesson; $('#topic-description').textContent = `Learn ${lesson} in the ${section.title} module.`; $('#topic-theory').innerHTML = buildLessonTheory(lesson, section, codeFor(lesson)); $('#topic-practice').innerHTML = `<ol class="cs-lesson-list">${section.lessons.map((item) => `<li>${item}</li>`).join('')}</ol>`; $('#code-editor').value = codeFor(lesson); $('#code-output').textContent = 'Ready to execute C# code. Click Run Code.'; $('#progress-fill').style.width = `${((sectionIndex + 1) / sections.length) * 100}%`; $('#progress-text').textContent = `${sectionIndex + 1} of ${sections.length} modules completed`; $('#progress-note').textContent = `${section.title}: ${lesson}`; updateNavigation(); }
function updateNavigation() { $('#prev-topic-btn').disabled = activeSection === 0; $('#next-topic-btn').disabled = activeSection === sections.length - 1; }
function updateThemeIcon() { const icon = themeToggle?.querySelector('i'); const light = document.body.classList.contains('light-theme'); if (icon) icon.className = light ? 'fa-solid fa-moon' : 'fa-solid fa-sun'; themeToggle?.setAttribute('aria-label', light ? 'Switch to dark mode' : 'Switch to light mode'); }
if (localStorage.getItem('theme') === 'light') document.body.classList.add('light-theme'); updateThemeIcon();
themeToggle?.addEventListener('click', () => { document.body.classList.toggle('light-theme'); localStorage.setItem('theme', document.body.classList.contains('light-theme') ? 'light' : 'dark'); updateThemeIcon(); });
const menuToggle = document.querySelector('.menu-toggle'); const navMenu = document.querySelector('.nav-menu'); menuToggle?.addEventListener('click', () => { const open = navMenu?.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(open)); });
$('#prev-topic-btn').addEventListener('click', () => loadLesson(Math.max(0, activeSection - 1), 0)); $('#next-topic-btn').addEventListener('click', () => loadLesson(Math.min(sections.length - 1, activeSection + 1), 0)); $('#reset-code-btn').addEventListener('click', () => { $('#code-editor').value = codeFor(sections[activeSection].lessons[activeLesson]); $('#code-output').textContent = 'Ready to execute C# code. Click Run Code.'; }); $('#copy-code-btn').addEventListener('click', async () => { await navigator.clipboard?.writeText($('#code-editor').value); $('#code-output').textContent = 'Code copied to clipboard.'; });
$('#run-code-btn').addEventListener('click', async () => { const source = $('#code-editor').value.trim(); const output = $('#code-output'); if (!source) { output.textContent = 'Please write some C# code first!'; return; } output.textContent = 'Compiling and executing...'; try { const response = await fetch('https://ce.judge0.com/submissions?base64_encoded=false&wait=true', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ language_id: 51, source_code: source, stdin: '' }) }); if (!response.ok) throw new Error('Execution service unavailable'); const result = await response.json(); output.textContent = [result.stdout, result.stderr, result.compile_output, result.message].filter(Boolean).join('\n').trim() || 'Program finished with no output.'; } catch (error) { output.textContent = 'Unable to run code. Check your internet connection and try again.'; } });
const authModal = $('#auth-modal'); $('#auth-btn')?.addEventListener('click', () => { authModal.classList.add('open'); authModal.setAttribute('aria-hidden', 'false'); }); $('#auth-close')?.addEventListener('click', () => { authModal.classList.remove('open'); authModal.setAttribute('aria-hidden', 'true'); }); $('#auth-form')?.addEventListener('submit', (event) => { event.preventDefault(); alert(`Welcome ${$('#auth-email').value}!`); authModal.classList.remove('open'); event.target.reset(); }); authModal?.addEventListener('click', (event) => { if (event.target === authModal) authModal.classList.remove('open'); });
renderTopics(); updateNavigation();
