window.subjectCourse = {
  subject: "CSS",
  modules: [
    ["CSS Introduction", "What is CSS?|Why CSS is Used?|Advantages of CSS|CSS Syntax|CSS Rules|CSS Comments|CSS Versions|CSS3|HTML vs CSS|How CSS Works?"],
    ["Ways to Add CSS", "Inline CSS|Internal CSS|External CSS|CSS Import|Difference Between Inline, Internal and External CSS"],
    ["CSS Selectors", "What are Selectors?|Universal Selector *|Element Selector|ID Selector #id|Class Selector .class|Grouping Selector|Attribute Selector|Descendant Selector|Child Selector|Adjacent Sibling Selector|General Sibling Selector|Pseudo-class Selector|Pseudo-element Selector"],
    ["CSS Colors", "Color Names|Hexadecimal Colors|RGB|RGBA|HSL|HSLA|Transparent Colors|Color Property"],
    ["CSS Backgrounds", "Background Color|Background Image|Background Repeat|Background Position|Background Size|Background Attachment|Background Shorthand|Multiple Background Images"],
    ["CSS Text", "Text Color|Text Alignment|Text Decoration|Text Transformation|Text Indentation|Letter Spacing|Word Spacing|Line Height|Text Shadow|White Space|Text Overflow"],
    ["CSS Fonts", "Font Family|Web-safe Fonts|Font Size|Font Style|Font Weight|Font Variant|Google Fonts|Custom Fonts|@font-face|Font Shorthand"],
    ["CSS Units", "Pixels px|Percentage %|em|rem|vh|vw|vmin|vmax|ch|ex|Absolute vs Relative Units"],
    ["CSS Box Model", "What is Box Model?|Content|Padding|Border|Margin|Width|Height|Box Sizing|box-sizing: border-box|Margin Collapse"],
    ["CSS Borders", "Border Width|Border Style|Border Color|Border Radius|Individual Borders|Border Shorthand|Rounded Borders|Circle using Border Radius"],
    ["CSS Margin & Padding", "Margin|Margin Top|Margin Right|Margin Bottom|Margin Left|Padding|Padding Top|Padding Right|Padding Bottom|Padding Left|Margin vs Padding"],
    ["CSS Width & Height", "Width|Height|Min-width|Max-width|Min-height|Max-height|Auto Width|Responsive Width|calc()"],
    ["CSS Display", "block|inline|inline-block|none|flex|grid|table|contents|Visibility|Display vs Visibility"],
    ["CSS Positioning", "Static|Relative|Absolute|Fixed|Sticky|Top|Right|Bottom|Left|Z-index|Positioning Examples"],
    ["CSS Overflow", "visible|hidden|scroll|auto|overflow-x|overflow-y|Text Overflow|Scrollable Containers"],
    ["CSS Flexbox", "What is Flexbox?|Flex Container|Flex Items|display: flex|Flex Direction|Flex Wrap|Justify Content|Align Items|Align Content|Align Self|Gap|Flex Grow|Flex Shrink|Flex Basis|Flex Shorthand|Order|Flexbox Layout Examples"],
    ["CSS Grid", "What is CSS Grid?|Grid Container|Grid Items|Columns|Rows|Grid Gap|Grid Template Columns|Grid Template Rows|Grid Column|Grid Row|Grid Area|grid-template-areas|Auto Columns|Auto Rows|Grid Alignment|Responsive Grid"],
    ["CSS Shadows", "Box Shadow|Text Shadow|Multiple Shadows|Shadow Blur|Shadow Spread|Shadow Offset|Modern Card Shadows"],
    ["CSS Gradients", "Linear Gradient|Radial Gradient|Conic Gradient|Gradient Direction|Multiple Color Stops|Gradient Backgrounds|Gradient Buttons"],
    ["CSS Opacity & Transparency", "Opacity|RGBA|Transparent Background|Transparent Borders|Hover Transparency"],
    ["CSS Pseudo-classes", ":hover|:active|:focus|:visited|:link|:first-child|:last-child|:nth-child()|:not()|:checked|:disabled|:enabled|:required|:valid|:invalid"],
    ["CSS Pseudo-elements", "::before|::after|::first-letter|::first-line|::selection|::placeholder|Pseudo-element Examples"],
    ["CSS Transitions", "What are Transitions?|Transition Property|Transition Duration|Transition Timing Function|Transition Delay|Transition Shorthand|Hover Transition Effects"],
    ["CSS Transforms", "translate()|rotate()|scale()|skew()|Transform Origin|2D Transforms|3D Transforms|Transform Examples"],
    ["CSS Animations", "What are Animations?|@keyframes|Animation Name|Animation Duration|Animation Delay|Animation Iteration Count|Animation Direction|Animation Timing Function|Animation Fill Mode|Animation Play State|Animation Shorthand|Loading Animations|Button Animations"],
    ["CSS Responsive Design", "What is Responsive Design?|Responsive Layout|Media Queries|@media|Mobile-first Design|Desktop-first Design|Responsive Images|Responsive Typography|Breakpoints|Mobile / Tablet / Desktop Layout"],
    ["CSS Functions", "calc()|min()|max()|clamp()|rgb()|rgba()|hsl()|var()|url()|linear-gradient()"],
    ["CSS Variables", "What are CSS Variables?|Creating Variables|--variable|Using var()|Global Variables|Local Variables|Changing Variables|CSS Variables with Themes|Dark/Light Mode"],
    ["CSS Forms", "Styling Input|Styling Labels|Styling Buttons|Textarea Styling|Select Styling|Checkbox Styling|Radio Button Styling|Focus Effects|Form Validation Styling"],
    ["CSS Tables", "Table Borders|Border Collapse|Table Width|Table Alignment|Table Padding|Table Hover|Zebra Striped Tables|Responsive Tables"],
    ["CSS Lists", "List Style Type|List Style Image|List Style Position|Custom List Icons|Horizontal Lists|Navigation Lists"],
    ["CSS Navigation Bars", "Basic Navbar|Horizontal Navbar|Vertical Navbar|Dropdown Menu|Sticky Navbar|Responsive Navbar|Mobile Menu|Hamburger Menu"],
    ["CSS Cards & Components", "Basic Card|Profile Card|Course Card|Product Card|Pricing Card|Image Card|Hover Card|Glassmorphism Card|Neumorphism Card"],
    ["CSS Advanced Layout", "Flexbox vs Grid|Multi-column Layout|CSS Columns|Container Queries|aspect-ratio|object-fit|object-position|Layered Layouts"],
    ["CSS Modern Effects", "Glassmorphism|Neumorphism|Gradient Effects|Glow Effects|Blur Effects|Backdrop Filter|Modern Hover Effects|3D Card Effects"],
    ["CSS Accessibility", "Accessible Colors|Color Contrast|Focus Indicators|Readable Font Sizes|Reduced Motion|prefers-reduced-motion|Accessible Forms"],
    ["CSS Best Practices", "Clean CSS|Proper Naming|Reusable Classes|Avoiding Duplicate CSS|CSS Organization|Responsive First Approach|Using Variables|Avoiding !important|Maintainable CSS"],
    ["CSS Practical Projects", "Personal Portfolio|Login Page|Registration Form|Navigation Bar|Responsive Landing Page|Course Cards|Pricing Cards|Image Gallery|Responsive Blog|Admin Dashboard|E-commerce Product Page|Animated Website"]
  ].map(([title, topics]) => ({
    title,
    topics: topics.split("|").map((topic) => topic.trim())
  }))
};
