const $=s=>document.querySelector(s);const topicList=$('#topic-list');
const sections=[
['Introduction to DBMS','What is Data?|What is Database?|What is DBMS?|Need for DBMS|Advantages of DBMS|Disadvantages of DBMS|Applications of DBMS|DBMS vs File System|DBMS vs RDBMS'],
['Database Architecture','Database Architecture|1-Tier Architecture|2-Tier Architecture|3-Tier Architecture|Client-Server Architecture|Database Server'],
['DBMS Users','Database Administrator|Database Designer|Application Programmer|End Users|System Analyst'],
['Data Models','What is Data Model?|Hierarchical Model|Network Model|Relational Model|Object-Oriented Model|Object-Relational Model'],
['Database Schema','Schema|Instance|Physical Schema|Logical Schema|External Schema|Three-Schema Architecture|Data Independence'],
['ER Model','Entity|Entity Set|Attributes|Types of Attributes|Simple Attribute|Composite Attribute|Single-Valued Attribute|Multi-Valued Attribute|Derived Attribute|Key Attribute|Relationship|Relationship Set|Degree of Relationship|Cardinality|Participation Constraints|ER Diagram|Weak Entity|Strong Entity'],
['Relational Model','Relation|Tuple|Attribute|Domain|Relation Schema|Relation Instance|Degree|Cardinality|Relational Database'],
['Keys','Super Key|Candidate Key|Primary Key|Alternate Key|Foreign Key|Composite Key|Unique Key|Surrogate Key'],
['Integrity Constraints','Domain Constraint|Entity Integrity|Referential Integrity|Key Constraint|NOT NULL|UNIQUE|CHECK|DEFAULT'],
['Relational Algebra','Introduction to Relational Algebra|Selection|Projection|Union|Set Difference|Cartesian Product|Rename|Intersection|Join|Natural Join|Outer Join|Division'],
['SQL Introduction','What is SQL?|Features of SQL|SQL Commands|DDL|DML|DQL|DCL|TCL'],
['SQL Basics','CREATE|ALTER|DROP|TRUNCATE|INSERT|UPDATE|DELETE|SELECT'],
['SQL Operators','Arithmetic Operators|Comparison Operators|Logical Operators|BETWEEN|IN|LIKE|IS NULL|NOT'],
['SQL Functions','Aggregate Functions|COUNT()|SUM()|AVG()|MIN()|MAX()|String Functions|Date Functions|Numeric Functions'],
['SQL Clauses','WHERE|ORDER BY|GROUP BY|HAVING|DISTINCT|LIMIT|OFFSET'],
['SQL Joins','What is Join?|INNER JOIN|LEFT JOIN|RIGHT JOIN|FULL JOIN|CROSS JOIN|SELF JOIN'],
['SQL Subqueries','What is Subquery?|Single-Row Subquery|Multi-Row Subquery|Nested Subquery|Correlated Subquery|EXISTS|NOT EXISTS'],
['SQL Views','What is View?|Creating View|Updating View|Dropping View|Advantages of Views'],
['SQL Indexes','What is Index?|Creating Index|Unique Index|Clustered Index|Non-Clustered Index|Advantages and Disadvantages'],
['SQL Constraints','PRIMARY KEY|FOREIGN KEY|UNIQUE|NOT NULL|CHECK|DEFAULT'],
['Normalization','What is Normalization?|Need for Normalization|Data Redundancy|Update Anomaly|Insert Anomaly|Delete Anomaly|Functional Dependency|1NF|2NF|3NF|BCNF|4NF|5NF'],
['Functional Dependency','Functional Dependency|Full Functional Dependency|Partial Dependency|Transitive Dependency|Trivial Dependency|Non-Trivial Dependency|Closure of Attributes'],
['Transactions','What is Transaction?|Transaction States|Active State|Partially Committed|Committed|Failed|Aborted|ACID Properties|Atomicity|Consistency|Isolation|Durability'],
['Transaction Control','COMMIT|ROLLBACK|SAVEPOINT|TCL Commands'],
['Concurrency Control','What is Concurrency?|Need for Concurrency Control|Lost Update Problem|Dirty Read|Unrepeatable Read|Phantom Read|Serial Schedule|Non-Serial Schedule|Conflict Serializability|View Serializability'],
['Locking','Lock|Shared Lock|Exclusive Lock|Lock Compatibility|Two-Phase Locking|Strict 2PL|Deadlock|Deadlock Prevention|Deadlock Detection'],
['Database Recovery','What is Recovery?|Types of Failures|Transaction Failure|System Failure|Disk Failure|Log-Based Recovery|Checkpoints|Shadow Paging|Undo|Redo|Undo/Redo'],
['Storage & File Organization','Physical Storage|Magnetic Disk|SSD|Storage Hierarchy|File Organization|Heap File|Sequential File|Hash File|Indexed File'],
['Database Indexing','Primary Index|Secondary Index|Clustering Index|Multilevel Index|B-Tree|B+ Tree|Hash Indexing'],
['Distributed Database','What is Distributed Database?|Distributed DBMS|Advantages|Disadvantages|Data Fragmentation|Horizontal Fragmentation|Vertical Fragmentation|Replication|Distributed Transactions'],
['NoSQL Database','What is NoSQL?|SQL vs NoSQL|Key-Value Database|Document Database|Column Database|Graph Database|Advantages of NoSQL|Applications of NoSQL'],
['Database Security','Database Security|Authentication|Authorization|Access Control|Roles|Privileges|GRANT|REVOKE|SQL Injection|Database Encryption|Backup Security'],
['Database Administration','Database Administrator|User Management|Backup|Recovery|Performance Monitoring|Database Maintenance|Storage Management'],
['Advanced DBMS','Query Processing|Query Optimization|Cost-Based Optimization|Distributed Query Processing|Data Warehousing|OLTP|OLAP|Data Mining|Big Data Databases'],
['Database Projects','Student Database|Library Management Database|Hospital Database|Employee Management Database|Banking Database|E-Commerce Database|College Management Database|Final DBMS Project']
].map(([title,lessons])=>({title,lessons:lessons.split('|')}));
const allLessons=sections.flatMap(s=>s.lessons);let activeSection=0,activeLesson=0;
const profile=lesson=>{let n=lesson.toLowerCase();if(n.includes('key'))return ['identifies rows and connects related tables','PRIMARY KEY (student_id)','Each row is uniquely identified.'];if(n.includes('join'))return ['combines rows from related tables using a matching condition','SELECT * FROM Student s INNER JOIN Course c ON s.course_id=c.id;','Matching rows from both tables are returned.'];if(n.includes('normal'))return ['organizes tables to reduce duplicate data and update anomalies','Student(StudentID, Name, CourseID)','Each fact is stored in the appropriate relation.'];if(n.includes('transaction')||n.includes('acid'))return ['groups database operations into one reliable unit of work','START TRANSACTION; UPDATE Account SET balance=balance-100; COMMIT;','All valid changes are committed together.'];if(n.includes('select')||n.includes('where')||n.includes('sql')||n.includes('create')||n.includes('insert')||n.includes('update'))return ['uses SQL to define, read, and change structured data','SELECT name, course FROM Student WHERE age > 18;','Only rows matching the condition are returned.'];return [`explains the database concept named ${lesson}`,`-- Apply ${lesson} to a Student database`,`The concept helps store, organize, or safely access data.`];};
const topicImage=lesson=>{const pools={intro:['photo-1544383835-bda2bc66a55d','photo-1516321318423-f06f85e504b3','photo-1558494949-ef010cbdcc31'],sql:['photo-1551288049-bebda4e38f71','photo-1518186285589-2f7649de83e0','photo-1555066931-4365d14bab8c','photo-1518770660439-4636190af475'],security:['photo-1563013544-824ae1b704d3','photo-1451187580459-43490279c0fa','photo-1563986768609-322da13575f3'],data:['photo-1516321318423-f06f85e504b3','photo-1551288049-bebda4e38f71','photo-1497366754035-f200968a6e72'],storage:['photo-1597852074816-d933c7d2b988','photo-1518770660439-4636190af475','photo-1558494949-ef010cbdcc31']};const n=lesson.toLowerCase();const pool=n.includes('security')||n.includes('authentication')||n.includes('authorization')||n.includes('injection')||n.includes('grant')||n.includes('revoke')?pools.security:n.includes('sql')||n.includes('query')||n.includes('select')||n.includes('join')||n.includes('table')||n.includes('index')||n.includes('view')?pools.sql:n.includes('storage')||n.includes('file')||n.includes('disk')||n.includes('backup')?pools.storage:n.includes('data')||n.includes('json')||n.includes('nosql')||n.includes('entity')||n.includes('relationship')?pools.data:pools.intro;const hash=[...lesson].reduce((total,char)=>total+char.charCodeAt(0),0);return `https://images.unsplash.com/${pool[hash%pool.length]}?auto=format&fit=crop&w=1200&q=80`;};
const codeFor=lesson=>{const n=lesson.toLowerCase();if(n.includes('join'))return `-- ${lesson}\nSELECT s.Name, c.CourseName\nFROM Student s\nINNER JOIN Course c ON s.CourseID = c.CourseID;`;if(n.includes('key'))return `-- ${lesson}\nCREATE TABLE Student (\n    StudentID INT PRIMARY KEY,\n    Email VARCHAR(100) UNIQUE,\n    Name VARCHAR(50)\n);`;if(n.includes('normal')||n.includes('dependency'))return `-- ${lesson}\nCREATE TABLE StudentCourse (\n    StudentID INT,\n    CourseID INT,\n    PRIMARY KEY (StudentID, CourseID)\n);`;if(n.includes('transaction')||n.includes('commit')||n.includes('rollback')||n.includes('savepoint'))return `-- ${lesson}\nSTART TRANSACTION;\nUPDATE Account SET Balance = Balance - 500 WHERE AccountID = 1;\nCOMMIT;`;if(n.includes('index'))return `-- ${lesson}\nCREATE INDEX idx_student_name\nON Student(Name);\n\nSELECT * FROM Student WHERE Name = 'Aman';`;if(n.includes('view'))return `-- ${lesson}\nCREATE VIEW CSE_Students AS\nSELECT Name, Age FROM Student\nWHERE Course = 'CSE';`;if(n.includes('constraint')||n.includes('not null')||n.includes('unique')||n.includes('check')||n.includes('default'))return `-- ${lesson}\nCREATE TABLE Employee (\n    EmployeeID INT PRIMARY KEY,\n    Name VARCHAR(50) NOT NULL,\n    Salary DECIMAL(10,2) CHECK (Salary > 0)\n);`;if(n.includes('aggregate')||n.includes('count')||n.includes('sum')||n.includes('avg')||n.includes('min')||n.includes('max')||n.includes('group'))return `-- ${lesson}\nSELECT Course, COUNT(*) AS TotalStudents\nFROM Student\nGROUP BY Course;`;if(n.includes('insert'))return `-- ${lesson}\nINSERT INTO Student (RollNo, Name, Course, Age)\nVALUES (104, 'Neha', 'CSE', 20);`;if(n.includes('update'))return `-- ${lesson}\nUPDATE Student\nSET Course = 'IT'\nWHERE RollNo = 104;`;if(n.includes('delete'))return `-- ${lesson}\nDELETE FROM Student\nWHERE RollNo = 104;`;if(n.includes('drop')||n.includes('truncate')||n.includes('alter'))return `-- ${lesson}\nALTER TABLE Student\nADD Email VARCHAR(100);`;if(n.includes('subquer')||n.includes('exists'))return `-- ${lesson}\nSELECT Name FROM Student\nWHERE Age > (SELECT AVG(Age) FROM Student);`;if(n.includes('nosql')||n.includes('document')||n.includes('mongodb'))return `// ${lesson}\ndb.students.find({ course: 'CSE' });`;if(n.includes('security')||n.includes('grant')||n.includes('revoke')||n.includes('authorization'))return `-- ${lesson}\nGRANT SELECT ON Student TO analyst;\nREVOKE DELETE ON Student FROM analyst;`;if(n.includes('recovery')||n.includes('undo')||n.includes('redo')||n.includes('checkpoint'))return `-- ${lesson}\nCHECKPOINT;\n-- Recovery uses the log to undo or redo committed work`;return `-- ${lesson}\nCREATE TABLE Student (\n    RollNo INT PRIMARY KEY,\n    Name VARCHAR(50),\n    Course VARCHAR(30),\n    Age INT\n);\n\nSELECT * FROM Student;`;};
const tableFor=lesson=>{const n=lesson.toLowerCase();if(n.includes('join'))return '<tr><td>101</td><td>Aman</td><td>CSE</td><td>Database</td></tr><tr><td>102</td><td>Priya</td><td>IT</td><td>Networks</td></tr>';if(n.includes('transaction')||n.includes('account'))return '<tr><td>1</td><td>Aman</td><td>50000</td><td>Active</td></tr><tr><td>2</td><td>Priya</td><td>42000</td><td>Active</td></tr>';if(n.includes('key')||n.includes('constraint'))return '<tr><td>1</td><td>aman@example.com</td><td>Aman</td><td>CSE</td></tr><tr><td>2</td><td>priya@example.com</td><td>Priya</td><td>IT</td></tr>';return `<tr><td>${lesson}</td><td>DBMS</td><td>Lesson Example</td><td>Study and practice</td></tr><tr><td>${lesson} query</td><td>SQL</td><td>Related data</td><td>Ready</td></tr>`;};
const buildTheory=(lesson,section)=>{let[explanation,syntax,result]=profile(lesson);let code=codeFor(lesson);return `<div class="dbms-callout"><i class="fa-solid fa-star"></i><p><strong>${lesson}</strong> is an important topic in ${section.title}.</p></div><h3>What is ${lesson}?</h3><p>In the <strong>${section.title}</strong> module, ${lesson} ${explanation}. DBMS concepts help applications store, retrieve, secure, and process data reliably.</p><ul class="dbms-points"><li>Data is organized for accurate and fast access.</li><li>Constraints and transactions protect data correctness.</li><li>SQL makes database operations clear and repeatable.</li></ul><h3>Example of Database</h3><p>Consider a simple Student table in a database.</p><table class="data-table"><thead><tr><th>RollNo</th><th>Name</th><th>Course</th><th>Age</th></tr></thead><tbody><tr><td>101</td><td>Aman</td><td>CSE</td><td>19</td></tr><tr><td>102</td><td>Priya</td><td>IT</td><td>20</td></tr><tr><td>103</td><td>Rahul</td><td>CSE</td><td>19</td></tr></tbody></table><h3>Example: ${lesson}</h3><div class="sql-example"><div><strong>example.sql</strong><button class="copy-example" type="button">Copy Code</button></div><pre>${code}</pre></div><p><strong>Syntax:</strong> ${syntax}</p><p><strong>Expected result:</strong> ${result}</p><h3 class="lesson-reference-title">Key Points</h3><ul><li>Choose the correct table and columns.</li><li>Use constraints to prevent invalid data.</li><li>Test the query with normal and edge cases.</li></ul>`;};
function renderTopics(){topicList.innerHTML='';sections.forEach((section,si)=>{let button=document.createElement('button');button.type='button';button.className='dbms-topic';button.dataset.section=si;button.innerHTML=`<span>${si+1}. ${section.title}</span><i class="fa-solid fa-chevron-right topic-arrow"></i>`;let lessons=document.createElement('div');lessons.className='dbms-subtopics';lessons.id=`dbms-section-${si}`;section.lessons.forEach((lesson,li)=>{let b=document.createElement('button');b.type='button';b.className='dbms-subtopic';b.textContent=`${li+1}. ${lesson}`;b.addEventListener('click',()=>loadLesson(si,li));lessons.appendChild(b);});button.addEventListener('click',()=>{let open=lessons.classList.toggle('open');button.classList.toggle('expanded',open);if(open)loadLesson(si,0);});topicList.append(button,lessons);});$('#lesson-count').textContent=allLessons.length;}
function loadLesson(si,li){activeSection=si;activeLesson=li;let section=sections[si],lesson=section.lessons[li],box=$(`#dbms-section-${si}`);box.classList.add('open');topicList.querySelectorAll('.dbms-topic').forEach((b,i)=>{b.classList.toggle('active',i===si);b.classList.toggle('expanded',i===si);});topicList.querySelectorAll('.dbms-subtopic').forEach(b=>b.classList.remove('active'));box.querySelectorAll('.dbms-subtopic')[li].classList.add('active');$('#page-title').textContent=`${si+1}. ${section.title}`;$('#topic-title').textContent=lesson;$('#topic-description').textContent=`Learn ${lesson} as part of the ${section.title} module.`;$('#topic-theory').innerHTML=buildTheory(lesson,section);$('#topic-theory').style.setProperty('--topic-image',`url("${topicImage(lesson)}")`);const table=$('#topic-theory .data-table');if(table)table.innerHTML=`<thead><tr><th>Key</th><th>Name</th><th>Type</th><th>Value</th></tr></thead><tbody>${tableFor(lesson)}</tbody>`;$('#topic-practice').innerHTML=`<ol class="dbms-lesson-list">${section.lessons.map(x=>`<li>${x}</li>`).join('')}</ol>`;$('#code-editor').value=codeFor(lesson);$('#code-output').textContent='Database created successfully. Ready to execute SQL code.';$('#progress-fill').style.width=`${((si+1)/sections.length)*100}%`;$('#progress-text').textContent=`${si+1} of ${sections.length} modules completed`;$('#progress-note').textContent=`${section.title}: ${lesson}`;$('#prev-topic-btn').disabled=si===0;$('#next-topic-btn').disabled=si===sections.length-1;document.querySelectorAll('.copy-example').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard?.writeText(codeFor(lesson));b.textContent='Copied';}));}
renderTopics();loadLesson(0,0);$('#prev-topic-btn').addEventListener('click',()=>loadLesson(Math.max(0,activeSection-1),0));$('#next-topic-btn').addEventListener('click',()=>loadLesson(Math.min(sections.length-1,activeSection+1),0));$('#reset-code-btn').addEventListener('click',()=>{$('#code-editor').value=codeFor(sections[activeSection].lessons[activeLesson]);$('#code-output').textContent='Editor reset.';});$('#copy-code-btn').addEventListener('click',async()=>{await navigator.clipboard?.writeText($('#code-editor').value);$('#code-output').textContent='Code copied to clipboard.';});$('#run-code-btn').addEventListener('click',()=>{$('#code-output').textContent='Database created successfully. Query executed successfully.';});
const theme=$('#theme-toggle'),updateTheme=()=>{let light=document.body.classList.contains('light-theme');theme.querySelector('i').className=light?'fa-solid fa-moon':'fa-solid fa-sun';theme.setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode');};if(localStorage.getItem('theme')==='light')document.body.classList.add('light-theme');updateTheme();theme.addEventListener('click',()=>{document.body.classList.toggle('light-theme');localStorage.setItem('theme',document.body.classList.contains('light-theme')?'light':'dark');updateTheme();});const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-menu');menu?.addEventListener('click',()=>{let open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});const modal=$('#auth-modal'),auth=$('#auth-btn'),close=$('#auth-close'),form=$('#auth-form'),email=$('#auth-email');auth.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');email.focus();});close.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');});modal.addEventListener('click',e=>{if(e.target===modal)close.click();});form.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('dbmsUser',email.value);auth.textContent='Sign Out';close.click();});if(localStorage.getItem('dbmsUser'))auth.textContent='Sign Out';