const $=s=>document.querySelector(s);const topicList=$('#topic-list');
const sections=[
['Introduction to Operating System','What is Operating System?|Need for Operating System|Functions of OS|Goals of Operating System|Components of OS|OS as Resource Manager|OS as User Interface|Kernel|Shell|System Programs'],
['Types of Operating Systems','Batch Operating System|Multiprogramming OS|Multitasking OS|Time-Sharing OS|Multiprocessing OS|Distributed OS|Network OS|Real-Time OS|Embedded OS|Mobile Operating System'],
['Operating System Services','Program Execution|I/O Operations|File-System Manipulation|Communication|Error Detection|Resource Allocation|Accounting|Protection and Security'],
['System Calls','What are System Calls?|Types of System Calls|Process Control|File Management|Device Management|Information Maintenance|Communication|Protection|Examples of System Calls'],
['Operating System Structure','Simple Structure|Monolithic Structure|Layered Structure|Microkernel|Modular Structure|Hybrid Structure'],
['Process Management','What is a Process?|Program vs Process|Process States|Process State Diagram|Process Control Block (PCB)|Process Creation|Process Termination|Parent and Child Process|Process Scheduling|Context Switching'],
['Process Scheduling','Scheduling Queues|Ready Queue|Waiting Queue|Schedulers|Long-Term Scheduler|Short-Term Scheduler|Medium-Term Scheduler|Dispatcher|Context Switch'],
['CPU Scheduling','What is CPU Scheduling?|Scheduling Criteria|CPU Utilization|Throughput|Turnaround Time|Waiting Time|Response Time|Preemptive Scheduling|Non-Preemptive Scheduling'],
['CPU Scheduling Algorithms','FCFS|SJF|SRTF|Priority Scheduling|Round Robin|Multilevel Queue|Multilevel Feedback Queue|Gantt Chart|Scheduling Numerical Problems'],
['Threads','What is Thread?|Process vs Thread|Benefits of Threads|User-Level Threads|Kernel-Level Threads|Multithreading|Multithreading Models|Many-to-One|One-to-One|Many-to-Many'],
['Process Synchronization','What is Synchronization?|Race Condition|Critical Section|Critical Section Problem|Mutual Exclusion|Progress|Bounded Waiting|Peterson\'s Solution|Hardware Synchronization'],
['Synchronization Tools','Mutex|Semaphore|Binary Semaphore|Counting Semaphore|Monitor|Condition Variables|Spinlock'],
['Classical Synchronization Problems','Producer-Consumer Problem|Readers-Writers Problem|Dining Philosophers Problem|Sleeping Barber Problem'],
['Inter-Process Communication (IPC)','What is IPC?|Shared Memory|Message Passing|Pipes|Named Pipes|Sockets|Signals|Client-Server Communication'],
['Deadlocks','What is Deadlock?|Deadlock Conditions|Mutual Exclusion|Hold and Wait|No Preemption|Circular Wait|Resource Allocation Graph'],
['Deadlock Handling','Deadlock Prevention|Deadlock Avoidance|Deadlock Detection|Deadlock Recovery|Safe State|Unsafe State|Banker\'s Algorithm|Deadlock Detection Algorithm'],
['Memory Management','What is Memory Management?|Logical Address|Physical Address|Address Binding|Compile-Time Binding|Load-Time Binding|Execution-Time Binding|Swapping|Contiguous Memory Allocation'],
['Paging','What is Paging?|Pages|Frames|Page Table|Address Translation|TLB|Multilevel Paging|Inverted Page Table'],
['Segmentation','What is Segmentation?|Segment|Segment Table|Logical Address in Segmentation|Paging vs Segmentation'],
['Virtual Memory','What is Virtual Memory?|Demand Paging|Page Fault|Page Replacement|Thrashing|Copy-on-Write|Memory-Mapped Files'],
['Page Replacement Algorithms','FIFO|Optimal Page Replacement|LRU|Second Chance|Clock Algorithm|LFU|MFU|Page Replacement Numericals'],
['File System','What is File System?|File Concept|File Attributes|File Operations|File Types|File Structure|File Access Methods|Sequential Access|Direct Access|Indexed Access'],
['Directory Structure','Single-Level Directory|Two-Level Directory|Tree-Structured Directory|Acyclic Graph Directory|General Graph Directory'],
['File Allocation Methods','Contiguous Allocation|Linked Allocation|Indexed Allocation|File Allocation Table (FAT)|Free Space Management'],
['I/O Management','I/O Hardware|I/O Controller|Device Drivers|Interrupts|DMA|Buffering|Caching|Spooling'],
['Disk Management','Disk Structure|Disk Scheduling|FCFS Disk Scheduling|SSTF|SCAN|C-SCAN|LOOK|C-LOOK|Disk Scheduling Numericals'],
['Protection','Protection in OS|Protection Domain|Access Matrix|Access Control|Access Rights|Capability List|Access Control List'],
['Security','OS Security|Authentication|Authorization|Password Security|Malware|Virus|Worm|Trojan Horse|Spyware|Denial of Service|Security Policies'],
['Linux & Unix Concepts','Linux Introduction|Linux File System|Linux Commands|Processes in Linux|Linux Permissions|Users and Groups|Shell|Shell Scripting|Process Management in Linux'],
['Windows OS Concepts','Windows Architecture|Windows Processes|Windows Threads|Windows Memory Management|Windows File System|Windows Security'],
['Advanced Operating System','Distributed Systems|Distributed Processes|Distributed Scheduling|Distributed File System|Network Operating System|Cloud Operating Systems|Virtualization|Containers|Hypervisors'],
['OS Case Studies','Linux|Windows|Android|macOS|Unix'],
['OS Practical & Projects','Process Scheduling Simulator|Page Replacement Simulator|Disk Scheduling Simulator|Banker\'s Algorithm Simulator|File Management System|Memory Management Simulator|CPU Scheduling Project|Mini Operating System Concepts Project']
].map(([title,lessons])=>({title,lessons:lessons.split('|')}));
const allLessons=sections.flatMap(s=>s.lessons);let activeSection=0,activeLesson=0;
const images=['https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1597852074816-d933c7d2b988?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80'];
const imageFor=(section,lesson)=>{const n=section.title+' '+lesson;const hash=[...n].reduce((a,c)=>a+c.charCodeAt(0),0);return images[hash%images.length];};
const explain=lesson=>{const n=lesson.toLowerCase();if(n.includes('process')||n.includes('thread'))return ['manages a running program and the CPU work associated with it','Process = program in execution','The OS tracks state, registers, and resources for each running task.'];if(n.includes('schedul')||n.includes('fcfs')||n.includes('sjf')||n.includes('round robin'))return ['decides which ready process receives CPU time next','Waiting Time = Turnaround Time - Burst Time','A scheduling policy balances response, fairness, and throughput.'];if(n.includes('memory')||n.includes('page')||n.includes('frame')||n.includes('segment')||n.includes('virtual'))return ['organizes main memory and translates program addresses safely','Logical address -> MMU -> Physical address','The memory manager maps addresses and protects process spaces.'];if(n.includes('deadlock')||n.includes('mutex')||n.includes('semaphore')||n.includes('synchron'))return ['coordinates competing tasks so shared resources remain correct','lock(resource); critical_section(); unlock(resource);','Synchronization prevents races while avoiding unnecessary waiting.'];if(n.includes('file')||n.includes('directory')||n.includes('disk')||n.includes('storage'))return ['organizes persistent data and controls how storage is accessed','open -> read/write -> close','The file system gives applications a consistent view of devices.'];if(n.includes('security')||n.includes('permission')||n.includes('protection')||n.includes('authentication'))return ['controls who may access resources and what operations are allowed','user + permission -> access decision','Authentication identifies a user; authorization checks their rights.'];if(n.includes('kernel')||n.includes('shell')||n.includes('linux')||n.includes('windows'))return ['provides the interface between users, applications, and hardware','application -> system call -> kernel -> hardware','The OS hides hardware complexity behind controlled services.'];return [`explains the Operating System concept named ${lesson}`,`OS manages ${lesson} as part of the computer system`,`The concept improves resource use, reliability, or user interaction.`];};
const codeFor=lesson=>{const n=lesson.toLowerCase();if(n.includes('fcfs')||n.includes('sjf')||n.includes('round robin')||n.includes('schedul'))return `// ${lesson}\nint processes[] = {1, 2, 3};\nint burstTime[] = {5, 3, 8};\n// Apply the scheduling rule and calculate waiting time`;if(n.includes('page')||n.includes('fifo')||n.includes('lru'))return `// ${lesson}\nint referenceString[] = {1, 2, 3, 1, 4, 2};\nint frames = 3;\n// Simulate page replacement here`;if(n.includes('deadlock')||n.includes('banker'))return `// ${lesson}\nint available[] = {3, 3, 2};\nint allocation[3][3] = {};\n// Check whether the system is in a safe state`;if(n.includes('file')||n.includes('directory')||n.includes('disk'))return `// ${lesson}\nFILE *file = fopen("data.txt", "r");\n// Read or organize file-system data\nif (file != NULL) fclose(file);`;return `// ${lesson}\n#include <stdio.h>\n\nint main(void) {\n    printf("Operating System: ${lesson.replaceAll('"','') }\\n");\n    return 0;\n}`;};
const baseBuildTheory=(lesson,section)=>{const[e,s,r]=explain(lesson),code=codeFor(lesson),question=lesson.toLowerCase().startsWith('what is')?lesson:`What is ${lesson}?`;return `<div class="os-visual" style="background-image:linear-gradient(90deg,rgba(7,17,31,.08),rgba(7,17,31,.42)),url('${imageFor(section,lesson)}')"></div><div class="os-callout"><i class="fa-solid fa-star"></i><p><strong>${lesson}</strong> is an important concept in ${section.title}.</p></div><h3>${question}</h3><p>In the <strong>${section.title}</strong> module, <strong>${lesson}</strong> ${e}. Operating systems make this possible by coordinating CPU, memory, storage, devices, and users.</p><ul class="os-points"><li>It improves resource utilization and system performance.</li><li>It provides controlled access to hardware and shared resources.</li><li>It helps applications run reliably and independently.</li></ul><h3>Example: ${lesson}</h3><div class="os-example"><pre>${code}</pre></div><h3 class="os-reference-title">Key Points</h3><table class="os-table"><thead><tr><th>Concept</th><th>Explanation</th></tr></thead><tbody><tr><td>${lesson}</td><td>${s}</td></tr><tr><td>Expected result</td><td>${r}</td></tr><tr><td>Practice</td><td>Change the values and observe how the OS concept behaves.</td></tr></tbody></table>`;};
const visualFor=(section,lesson)=>{const n=`${section.title} ${lesson}`.toLowerCase();if(n.includes('process')||n.includes('thread')||n.includes('cpu')||n.includes('schedul'))return['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80','CPU and process scheduling'];if(n.includes('memory')||n.includes('page')||n.includes('paging')||n.includes('frame')||n.includes('segment')||n.includes('virtual'))return['https://images.unsplash.com/photo-1597852074816-d933c7d2b988?auto=format&fit=crop&w=1200&q=80','Memory and address management'];if(n.includes('file')||n.includes('directory')||n.includes('disk')||n.includes('storage')||n.includes('io'))return['https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80','File and device storage'];if(n.includes('deadlock')||n.includes('synchron')||n.includes('mutex')||n.includes('semaphore'))return['https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80','Synchronization and shared resources'];if(n.includes('security')||n.includes('protect')||n.includes('permission')||n.includes('malware'))return['https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80','Operating system security'];if(n.includes('linux')||n.includes('unix')||n.includes('shell')||n.includes('windows')||n.includes('kernel'))return['https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80','Kernel, shell, and operating system'];if(n.includes('network')||n.includes('distributed')||n.includes('server'))return['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80','Network and distributed systems'];return['https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80','Operating system architecture'];};
const buildTheory=(lesson,section)=>{const[image,caption]=visualFor(section,lesson);const content=baseBuildTheory(lesson,section);const visual=`<figure class="os-visual"><img src="${image}" alt="${caption} for ${lesson}"><figcaption>${caption} · ${lesson}</figcaption></figure>`;const richer=content.replace(/<div class="os-visual"[^>]*><\/div>/,visual).replace('</p><ul class="os-points">',`</p><p><strong>How it works:</strong> The operating system receives a request, checks the required resources, performs the operation through the kernel, and reports the result to the application.</p><p><strong>Real-world use:</strong> ${lesson} appears whenever a computer runs programs, shares hardware, stores data, or protects users from unsafe access.</p><ul class="os-points">`);return richer;};
function renderTopics(){topicList.innerHTML='';sections.forEach((section,si)=>{const b=document.createElement('button');b.type='button';b.className='os-topic';b.dataset.section=si;b.innerHTML=`<span>${si+1}. ${section.title}</span><i class="fa-solid fa-chevron-right topic-arrow"></i>`;const sub=document.createElement('div');sub.className='os-subtopics';sub.id=`os-section-${si}`;section.lessons.forEach((lesson,li)=>{const sb=document.createElement('button');sb.type='button';sb.className='os-subtopic';sb.textContent=`${li+1}. ${lesson}`;sb.addEventListener('click',()=>loadLesson(si,li));sub.appendChild(sb);});b.addEventListener('click',()=>{const wasOpen=sub.classList.contains('open');document.querySelectorAll('.os-subtopics').forEach(group=>group.classList.remove('open'));document.querySelectorAll('.os-topic').forEach(topic=>topic.classList.remove('expanded'));const open=!wasOpen;sub.classList.toggle('open',open);b.classList.toggle('expanded',open);if(open)loadLesson(si,0);});topicList.append(b,sub);});$('#lesson-count').textContent=allLessons.length;}
function loadLesson(si,li){activeSection=si;activeLesson=li;const section=sections[si],lesson=section.lessons[li],sub=$(`#os-section-${si}`);sub.classList.add('open');topicList.querySelectorAll('.os-topic').forEach((b,i)=>{b.classList.toggle('active',i===si);b.classList.toggle('expanded',i===si);});topicList.querySelectorAll('.os-subtopic').forEach(b=>b.classList.remove('active'));sub.querySelectorAll('.os-subtopic')[li].classList.add('active');$('#page-title').textContent=`${si+1}. ${section.title}`;$('#topic-title').textContent=lesson;$('#topic-description').textContent=`Learn ${lesson} as part of the ${section.title} module.`;$('#topic-theory').innerHTML=buildTheory(lesson,section);$('#topic-practice').innerHTML=`<ol class="os-lesson-list">${section.lessons.map(x=>`<li>${x}</li>`).join('')}</ol>`;$('#progress-fill').style.width=`${((si+1)/sections.length)*100}%`;$('#progress-text').textContent=`${si+1} of ${sections.length} modules completed`;$('#progress-note').textContent=`${section.title}: ${lesson}`;$('#prev-topic-btn').disabled=si===0;$('#next-topic-btn').disabled=si===sections.length-1;$('#bottom-prev').disabled=si===0;$('#bottom-next').disabled=si===sections.length-1;}
renderTopics();loadLesson(0,0);const movePrev=()=>loadLesson(Math.max(0,activeSection-1),0),moveNext=()=>loadLesson(Math.min(sections.length-1,activeSection+1),0);$('#prev-topic-btn').addEventListener('click',movePrev);$('#next-topic-btn').addEventListener('click',moveNext);$('#bottom-prev').addEventListener('click',movePrev);$('#bottom-next').addEventListener('click',moveNext);
const theme=$('#theme-toggle'),updateTheme=()=>{const light=document.body.classList.contains('light-theme');theme.querySelector('i').className=light?'fa-solid fa-moon':'fa-solid fa-sun';theme.setAttribute('aria-label',light?'Switch to dark mode':'Switch to light mode');};if(localStorage.getItem('theme')==='light')document.body.classList.add('light-theme');updateTheme();theme.addEventListener('click',()=>{document.body.classList.toggle('light-theme');localStorage.setItem('theme',document.body.classList.contains('light-theme')?'light':'dark');updateTheme();});const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-menu');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});const modal=$('#auth-modal'),auth=$('#auth-btn'),close=$('#auth-close'),form=$('#auth-form'),email=$('#auth-email');auth.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');email.focus();});close.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');});modal.addEventListener('click',e=>{if(e.target===modal)close.click();});form.addEventListener('submit',e=>{e.preventDefault();auth.textContent='Sign Out';close.click();});