const $ = selector => document.querySelector(selector);
const topicList = $('#topic-list');
const sections = [
['Introduction to Rust','What is Rust?|History of Rust|Features of Rust|Advantages of Rust|Applications of Rust|Rust vs C++|Rust vs C'],
['Rust Installation & Setup','Installing Rust|Installing rustup|Checking Rust Version|Installing Cargo|Setting up VS Code|First Rust Program'],
['Variables & Constants','Variables|Mutable Variables|Immutable Variables|Constants|Shadowing|Variable Scope'],
['Data Types','Scalar Types|Integer Types|Floating-Point Types|Boolean Type|Character Type|Compound Types|Tuples|Arrays|Type Inference|Type Conversion|Type Casting'],
['Operators','Arithmetic Operators|Comparison Operators|Logical Operators|Assignment Operators|Bitwise Operators|Range Operators|Operator Precedence'],
['Input & Output','println!()|print!()|stdin()|User Input|Reading Strings|Reading Numbers|Formatting Output'],
['Conditional Statements','if|if-else|else-if|Nested if|if as Expression|match'],
['Loops','loop|while|for|Nested Loops|break|continue|Loop as Expression'],
['Functions','Function Declaration|Function Parameters|Return Values|Multiple Parameters|Expressions and Statements|Recursive Functions|Closures'],
['Ownership','What is Ownership?|Ownership Rules|Move|Copy|Clone|Ownership with Functions|Ownership and Return Values'],
['Borrowing & References','References|Immutable References|Mutable References|Borrowing|Borrowing Rules|Multiple References|Dangling References'],
['Lifetimes','What are Lifetimes?|Lifetime Rules|Lifetime Annotations|Lifetime in Functions|Lifetime in Structs|\'static Lifetime'],
['Strings','String|&str|String Creation|String Input|String Methods|String Slicing|String Concatenation|String Formatting|UTF-8 and Unicode'],
['Structs','Defining Structs|Creating Struct Objects|Accessing Struct Fields|Mutable Structs|Tuple Structs|Unit Structs|Nested Structs|Struct Update Syntax'],
['Methods','Defining Methods|self|&self|&mut self|Associated Functions|Multiple Methods|Methods with Parameters'],
['Enums','Defining Enums|Enum Variants|Enum with Data|Enum Methods|Option|Some|None|Result'],
['Pattern Matching','match|Matching Values|Matching Enums|Matching Option|Matching Result|if let|while let|Pattern Guards'],
['Collections','Vector|Creating Vectors|Accessing Vector Elements|Adding Elements|Removing Elements|Iterating Vectors|HashMap|HashSet'],
['Modules & Packages','Modules|Packages|Crates|mod|use|pub|Visibility|Nested Modules|External Crates'],
['Error Handling','Errors in Rust|panic!|Recoverable Errors|Result|Option|unwrap()|expect()|Error Propagation|? Operator|Custom Errors'],
['Generics','What are Generics?|Generic Functions|Generic Structs|Generic Enums|Generic Methods|Generic Parameters|Generic Constraints'],
['Traits','What are Traits?|Defining Traits|Implementing Traits|Trait Methods|Trait Bounds|Multiple Traits|Default Trait Methods|Trait Objects'],
['Iterators','What are Iterators?|iter()|iter_mut()|into_iter()|next()|map()|filter()|collect()|Iterator Chaining'],
['Closures','Creating Closures|Closure Parameters|Closure Return Values|Closures with Variables|Closures as Functions|Closures with Iterators'],
['Smart Pointers','What are Smart Pointers?|Box<T>|Rc<T>|Arc<T>|RefCell<T>|Interior Mutability|Deref|Drop'],
['File Handling','Creating Files|Opening Files|Reading Files|Writing Files|Appending Files|BufReader|BufWriter|File Metadata'],
['Command Line','Command-Line Arguments|std::env|Reading Arguments|Environment Variables|Command-Line Applications'],
['Concurrency','Threads|Creating Threads|thread::spawn|Joining Threads|Message Passing|Channels|Shared State|Mutex|Arc|Race Conditions'],
['Async Programming','Async Programming|Futures|async|await|Async Functions|Async Tasks|Tokio|Async Channels'],
['Networking','TCP|UDP|TCP Client|TCP Server|HTTP|HTTP Client|HTTP Server|REST API'],
['JSON & Serialization','JSON|Serialization|Deserialization|Serde|JSON Objects|JSON Arrays|Reading JSON|Writing JSON'],
['Database','Database Connectivity|SQL|SQLite|PostgreSQL|MySQL|CRUD Operations|Database Queries|Connection Pooling'],
['Testing','Unit Testing|Test Functions|Assertions|assert!|assert_eq!|assert_ne!|Integration Testing|Documentation Testing|Benchmarking'],
['Macros','What are Macros?|Declarative Macros|macro_rules!|Macro Parameters|Procedural Macros|Attribute Macros|Derive Macros'],
['Unsafe Rust','What is Unsafe Rust?|Unsafe Blocks|Raw Pointers|Dereferencing Raw Pointers|Unsafe Functions|Unsafe Traits|Foreign Function Interface (FFI)'],
['Web Development','Rust Web Development|Web Frameworks|Actix Web|Axum|Routing|REST API|Middleware|Authentication|Web Server'],
['WebAssembly','What is WebAssembly?|Rust with WebAssembly|Installing wasm tools|Rust to WebAssembly|JavaScript Integration|WebAssembly Projects'],
['Rust Tools & Ecosystem','Cargo|Cargo.toml|Cargo Commands|Cargo Build|Cargo Run|Cargo Check|Cargo Test|Rustfmt|Clippy|Rust Analyzer'],
['Advanced Rust','Advanced Lifetimes|Advanced Traits|Associated Types|Trait Objects|Phantom Types|Higher-Ranked Trait Bounds|Advanced Generics|Zero-Cost Abstractions'],
['Rust Projects','CLI Calculator|File Manager|Todo Application|JSON API|REST API|Chat Application|Database Application|Web Application|Final Rust Project']
].map(([title, lessons]) => ({ title, lessons: lessons.split('|') }));
const allLessons = sections.flatMap(section => section.lessons);
let activeSection = 0;
let activeLesson = 0;
const profile = lesson => {
  const name = lesson.toLowerCase();
  if (name.includes('ownership') || name.includes('borrow') || name.includes('reference')) return ['controls how values are moved, borrowed, and released', 'let borrowed = &value;', 'The compiler checks that the reference remains valid.'];
  if (name.includes('loop') || name === 'for' || name === 'while' || name === 'break' || name === 'continue') return ['repeats work while a condition or iterator produces values', 'for value in values { println!("{value}"); }', 'Each value is processed in order.'];
  if (name.includes('function') || name.includes('closure')) return ['groups reusable behavior with typed parameters and return values', 'fn add(a: i32, b: i32) -> i32 { a + b }', 'Calling add(2, 3) returns 5.'];
  if (name.includes('struct') || name.includes('enum') || name.includes('trait')) return ['models data or behavior with an explicit, type-safe definition', 'struct User { name: String }', 'The type gives related data a clear shape.'];
  if (name.includes('error') || name.includes('result') || name.includes('option') || name.includes('panic')) return ['represents success, absence, or failure without hiding important control flow', 'let result: Result<i32, &str> = Ok(42);', 'The caller can match and handle the result.'];
  if (name.includes('thread') || name.includes('channel') || name.includes('async') || name.includes('mutex')) return ['helps coordinate work that runs concurrently or asynchronously', 'std::thread::spawn(|| println!("worker"));', 'Independent work can run without blocking the main task.'];
  if (name.includes('vector') || name.includes('hash') || name.includes('iterator') || name.includes('collection')) return ['organizes multiple values with safe access and useful standard-library operations', 'let values = vec![1, 2, 3];', 'The collection stores and provides access to its values.'];
  return [`explains the Rust concept named ${lesson}`, `// Apply ${lesson} in a small Rust program`, `The example demonstrates ${lesson}.`];
};
const codeFor = lesson => { const [,, result] = profile(lesson); return `fn main() {\n    let lesson = "${lesson.replaceAll('"','')}";\n    println!("{lesson}");\n    println!("${result.replaceAll('"','\\"')}");\n}`; };
const buildTheory = (lesson, section) => { const [explanation, syntax, result] = profile(lesson); const code = codeFor(lesson); const question = lesson.toLowerCase().startsWith('what is') ? lesson : `What is ${lesson}?`; return `<p><strong>${question}</strong></p><p>In the <strong>${section.title}</strong> module, <strong>${lesson}</strong> ${explanation}. Rust makes this behavior explicit through strong typing, ownership checks, and readable syntax.</p><p><strong>Syntax:</strong> ${syntax}</p><p><strong>Expected result:</strong> ${result}</p><div class="lesson-example"><h4>Example</h4><pre>${code}</pre></div><h4 class="lesson-reference-title">Remember</h4><ul><li>Use <code>cargo fmt</code> to format Rust code.</li><li>Prefer explicit types and clear ownership boundaries.</li><li>Compile early with <code>cargo check</code> and test edge cases.</li></ul><h4 class="lesson-reference-title">Topic Reference</h4><table class="lesson-table"><thead><tr><th>Item</th><th>Lesson-specific detail</th></tr></thead><tbody><tr><td>Concept</td><td>${lesson}</td></tr><tr><td>Syntax</td><td>${syntax}</td></tr><tr><td>Result</td><td>${result}</td></tr><tr><td>Practice</td><td>Change the example and predict the new result.</td></tr></tbody></table>`; };
function renderTopics() { topicList.innerHTML = ''; sections.forEach((section, sectionIndex) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'rust-topic'; button.dataset.section = sectionIndex; button.innerHTML = `<span>${sectionIndex + 1}. ${section.title}</span><i class="fa-solid fa-chevron-right topic-arrow" aria-hidden="true"></i>`; const lessons = document.createElement('div'); lessons.className = 'rust-subtopics'; lessons.id = `rust-section-${sectionIndex}`; section.lessons.forEach((lesson, lessonIndex) => { const lessonButton = document.createElement('button'); lessonButton.type = 'button'; lessonButton.className = 'rust-subtopic'; lessonButton.textContent = `${lessonIndex + 1}. ${lesson}`; lessonButton.addEventListener('click', () => loadLesson(sectionIndex, lessonIndex)); lessons.appendChild(lessonButton); }); button.addEventListener('click', () => { const open = lessons.classList.toggle('open'); button.classList.toggle('expanded', open); if (open) loadLesson(sectionIndex, 0); }); topicList.append(button, lessons); }); $('#lesson-count').textContent = allLessons.length; }
function loadLesson(sectionIndex, lessonIndex) { activeSection = sectionIndex; activeLesson = lessonIndex; const section = sections[sectionIndex]; const lesson = section.lessons[lessonIndex]; const sectionButton = topicList.querySelector(`[data-section="${sectionIndex}"]`); const lessonButtons = topicList.querySelectorAll(`#rust-section-${sectionIndex} .rust-subtopic`); const lessons = $(`#rust-section-${sectionIndex}`); lessons.classList.add('open'); sectionButton.classList.add('expanded', 'active'); lessonButtons.forEach((button, index) => button.classList.toggle('active', index === lessonIndex)); topicList.querySelectorAll('.rust-topic').forEach((button, index) => button.classList.toggle('active', index === sectionIndex)); $('#page-title').textContent = `${sectionIndex + 1}. ${section.title}`; $('#topic-title').textContent = lesson; $('#topic-description').textContent = `Learn ${lesson} as part of the ${section.title} module.`; $('#topic-theory').innerHTML = buildTheory(lesson, section); $('#topic-practice').innerHTML = `<ol class="rust-lesson-list">${section.lessons.map(item => `<li>${item}</li>`).join('')}</ol>`; $('#code-editor').value = codeFor(lesson); $('#code-output').textContent = 'Ready to execute Rust code. Click Run Code.'; $('#progress-fill').style.width = `${((sectionIndex + 1) / sections.length) * 100}%`; $('#progress-text').textContent = `${sectionIndex + 1} of ${sections.length} modules completed`; $('#progress-note').textContent = `${section.title}: ${lesson}`; $('#prev-topic-btn').disabled = sectionIndex === 0; $('#next-topic-btn').disabled = sectionIndex === sections.length - 1; }
renderTopics(); loadLesson(0, 0);
$('#prev-topic-btn').addEventListener('click', () => loadLesson(Math.max(0, activeSection - 1), 0)); $('#next-topic-btn').addEventListener('click', () => loadLesson(Math.min(sections.length - 1, activeSection + 1), 0)); $('#reset-code-btn').addEventListener('click', () => { $('#code-editor').value = codeFor(sections[activeSection].lessons[activeLesson]); $('#code-output').textContent = 'Ready to execute Rust code. Click Run Code.'; }); $('#copy-code-btn').addEventListener('click', async () => { await navigator.clipboard?.writeText($('#code-editor').value); $('#code-output').textContent = 'Code copied to clipboard.'; }); $('#run-code-btn').addEventListener('click', () => { $('#code-output').textContent = 'Rust code is ready. Run it locally with:\ncargo run\n\nThis browser editor does not compile Rust locally.'; });
const themeToggle = $('#theme-toggle'); const updateTheme = () => { const light = document.body.classList.contains('light-theme'); themeToggle.querySelector('i').className = light ? 'fa-solid fa-moon' : 'fa-solid fa-sun'; themeToggle.setAttribute('aria-label', light ? 'Switch to dark mode' : 'Switch to light mode'); }; if (localStorage.getItem('theme') === 'light') document.body.classList.add('light-theme'); updateTheme(); themeToggle.addEventListener('click', () => { document.body.classList.toggle('light-theme'); localStorage.setItem('theme', document.body.classList.contains('light-theme') ? 'light' : 'dark'); updateTheme(); });
const menuToggle = document.querySelector('.menu-toggle'); const navMenu = document.querySelector('.nav-menu'); menuToggle?.addEventListener('click', () => { const open = navMenu.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(open)); });
const authModal = $('#auth-modal'); const authButton = $('#auth-btn'); const authClose = $('#auth-close'); const authForm = $('#auth-form'); const authEmail = $('#auth-email'); const authStatus = document.querySelector('.auth-help'); const closeAuth = () => { authModal.classList.remove('open'); authModal.setAttribute('aria-hidden', 'true'); }; authButton.addEventListener('click', () => { if (localStorage.getItem('rustLearnUser')) { localStorage.removeItem('rustLearnUser'); authButton.textContent = 'Sign In'; authStatus.textContent = 'You have been signed out.'; } else { authModal.classList.add('open'); authModal.setAttribute('aria-hidden', 'false'); authEmail.focus(); } }); authClose.addEventListener('click', closeAuth); authModal.addEventListener('click', event => { if (event.target === authModal) closeAuth(); }); authForm.addEventListener('submit', event => { event.preventDefault(); localStorage.setItem('rustLearnUser', authEmail.value.trim()); authButton.textContent = 'Sign Out'; authStatus.textContent = `Signed in as ${authEmail.value.trim()}.`; closeAuth(); }); if (localStorage.getItem('rustLearnUser')) authButton.textContent = 'Sign Out';
